// Generated by work/prepare-blue-hour-seasons.py. All layers share mother-image coordinates.
export const blueHourSeasons = {
  "width": 1672,
  "height": 941,
  "day": {
    "complete": "/art/blue-hour/seasons/day/complete.webp",
    "character": "/art/blue-hour/seasons/day/character.webp",
    "landscape": "/art/blue-hour/seasons/day/landscape.webp",
    "body": "/art/blue-hour/seasons/day/body.webp",
    "leftHair": "/art/blue-hour/seasons/day/leftHair.webp",
    "rightHair": "/art/blue-hour/seasons/day/rightHair.webp",
    "foreground": "/art/blue-hour/seasons/day/foreground.webp",
    "canopy": "/art/blue-hour/seasons/day/canopy.webp",
    "eyesHalf": "/art/blue-hour/seasons/day/eyesHalf.webp",
    "eyesClosed": "/art/blue-hour/seasons/day/eyesClosed.webp",
    "useSplitCharacter": true,
    "useCanopy": true,
    "eyePatches": true,
    "bodyBottom": 1,
    "registration": {
      "status": "registered",
      "hair": "derived from original character using registered body mask",
      "characterTransform": [
        [
          0.8066110610961914,
          -0.0031912035774439573,
          241.68746948242188
        ],
        [
          0.0031912035774439573,
          0.8066110610961914,
          38.32389831542969
        ]
      ],
      "eyeCenters": [
        [
          1095.9229736328125,
          236.9064483642578
        ],
        [
          1152.519775390625,
          203.25216674804688
        ]
      ]
    }
  },
  "night": {
    "complete": "/art/blue-hour/seasons/night/complete.webp",
    "character": "/art/blue-hour/seasons/night/character.webp",
    "landscape": "/art/blue-hour/seasons/night/landscape.webp",
    "body": "/art/blue-hour/seasons/night/body.webp",
    "leftHair": "/art/blue-hour/seasons/night/leftHair.webp",
    "rightHair": "/art/blue-hour/seasons/night/rightHair.webp",
    "foreground": "/art/blue-hour/seasons/night/foreground.webp",
    "canopy": "/art/blue-hour/seasons/night/canopy.webp",
    "eyesHalf": "/art/blue-hour/seasons/night/eyesHalf.webp",
    "eyesClosed": "/art/blue-hour/seasons/night/eyesClosed.webp",
    "useSplitCharacter": true,
    "useCanopy": true,
    "eyePatches": true,
    "bodyBottom": 1,
    "registration": {
      "status": "registered",
      "hair": "derived from original character using registered body mask",
      "characterTransform": [
        [
          0.8452678918838501,
          -0.004800484981387854,
          228.10403442382812
        ],
        [
          0.004800484981387854,
          0.8452678918838501,
          71.05525970458984
        ]
      ],
      "eyeCenters": [
        [
          1177.98876953125,
          259.8789367675781
        ],
        [
          1235.64453125,
          228.93045043945312
        ]
      ]
    }
  }
} as const;
