import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import sharp from 'sharp';
import net from 'node:net';

test('isolated HTTP workflow: selection, review, build, search index, withdrawal, source preservation',async t=>{
 const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'publisher-http-'));
 const site=path.join(root,'site'),vault=path.join(root,'vault'),state=path.join(root,'private');
 await fs.mkdir(path.join(site,'src/pages'),{recursive:true});await fs.mkdir(vault);
 await fs.symlink(path.join(project,'node_modules'),path.join(site,'node_modules'),'junction');
 await fs.writeFile(path.join(site,'package.json'),'{"type":"module"}');
 await fs.writeFile(path.join(site,'astro.config.mjs'),'export default { site: "https://fixture.invalid", vite: { cacheDir: ".vite-test-cache" } };');
 await fs.writeFile(path.join(site,'src/pages/index.astro'),`---
import fs from 'node:fs/promises';
const files=await fs.readdir('content/published/notes');
const texts=await Promise.all(files.map(f=>fs.readFile('content/published/notes/'+f,'utf8')));
---
<html lang="zh-CN"><head><title>测试网站</title></head><body data-pagefind-body><h1>测试网站</h1>{texts.map(s=><pre>{s}</pre>)}</body></html>`);
 const raw='# 公开测试\n\nOnly selected material.\n\n![[pic.png]]';
 await fs.writeFile(path.join(vault,'Public.md'),raw);await fs.writeFile(path.join(vault,'Secret.md'),'DO_NOT_EXPORT_TEST_SECRET');
 await fs.writeFile(path.join(vault,'pic.png'),await sharp({create:{width:80,height:80,channels:4,background:{r:30,g:80,b:90,alpha:.5}}}).png().toBuffer());
 const probe=net.createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
 const child=spawn(process.execPath,[path.join(project,'tools/publisher/server.mjs')],{cwd:project,windowsHide:true,env:{...process.env,PUBLISHER_SITE:site,PUBLISHER_VAULT:vault,PUBLISHER_STATE:state,PUBLISHER_PORT:String(port),PUBLISHER_PREVIEW_URL:'http://127.0.0.1:4325/',ASTRO_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});
 let log='';child.stderr.on('data',d=>log+=d);
 t.after(async()=>{if(child.exitCode===null){const stopped=once(child,'exit');child.kill();await stopped}await fs.rm(root,{recursive:true,force:true,maxRetries:4,retryDelay:200})});
 await Promise.race([once(child.stdout,'data'),once(child,'exit').then(()=>{throw Error(log)})]);
 const base=`http://127.0.0.1:${port}`;
 const health=await fetch(base+'/api/health').then(r=>r.json());assert.match(health.version,/^[a-f0-9]{64}$/);assert.deepEqual({...health,version:undefined},{service:'garden-publisher',site,previewUrl:'http://127.0.0.1:4325/',version:undefined});
 const html=await fetch(base).then(r=>r.text()),token=html.match(/const token='([a-f0-9]+)'/)[1];
 assert.match(html,/href="http:\/\/127\.0\.0\.1:4325\/"/);
 const stylesheet=await fetch(base+'/publisher.css');assert.equal(stylesheet.status,200);assert.match(stylesheet.headers.get('content-type'),/text\/css/);assert.match(await stylesheet.text(),/color-scheme:\s*dark/);
 const call=async(route,data)=>{const response=await fetch(base+'/api/'+route,{method:data===undefined?'GET':'POST',headers:{'X-Publisher-Token':token,...(data===undefined?{}:{Origin:base,'Content-Type':'application/json'})},...(data===undefined?{}:{body:JSON.stringify(data)})});const body=await response.json();assert.equal(response.status,200,JSON.stringify(body));return body};
 assert.equal((await fetch(base+'/api/scan')).status,403);
 assert.equal((await fetch(base+'/api/deploy/status')).status,403);
 assert.equal((await fetch(base+'/api/deploy/start',{method:'POST',headers:{'X-Publisher-Token':token,'Content-Type':'application/json'},body:'{}'})).status,403);
 const deployment=await call('deploy/status');assert.equal(deployment.busy,false);assert.equal(deployment.phase,'idle');
 const deploymentReview=await call('deploy/review',{});assert.equal(deploymentReview.canPublish,false);assert.ok(deploymentReview.blockers.length);
 assert.equal((await fetch(base+'/api/select',{method:'POST',headers:{'X-Publisher-Token':token,Origin:'https://example.invalid','Content-Type':'application/json'},body:'{}'})).status,403);
 assert.deepEqual((await call('scan')).selected,[]);
 await call('select',{selected:['Public.md'],assets:{'pic.png':'lossless'},metadata:{'Public.md':{section:'tutorials',tags:['Computer Graphics'],series:'HTTP 测试系列'}}});let plan=await call('analyze',{});assert.deepEqual(plan.errors,[]);assert.deepEqual(plan.assetModes,{'pic.png':'lossless'});
 assert.equal(plan.notes[0].metadata.section,'tutorials');assert.deepEqual(plan.notes[0].metadata.tags,['Computer Graphics']);assert.deepEqual(plan.metadata['Public.md'],{section:'tutorials',tags:['Computer Graphics'],series:'HTTP 测试系列'});assert.equal(plan.scannedNotes.find(n=>n.path==='Public.md').metadata.section,'tutorials');
 const thumb=await fetch(base+'/api/thumbnail?id='+plan.id+'&key='+encodeURIComponent(plan.assets[0].key),{headers:{'X-Publisher-Token':token}});assert.equal(thumb.status,200);assert.match(thumb.headers.get('content-type'),/image/);
 const denied=await fetch(base+'/api/prepare',{method:'POST',headers:{'X-Publisher-Token':token,Origin:base,'Content-Type':'application/json'},body:JSON.stringify({id:plan.id,approved:[]})});assert.equal(denied.status,400);
 let stage=await call('prepare',{id:plan.id,approved:plan.assets.map(a=>a.key)});
 const preview=await call('stage?id='+stage.id+'&slug='+stage.notes[0].slug);assert.match(preview.markdown,/公开测试/);assert.doesNotMatch(preview.markdown,/DO_NOT_EXPORT/);
 const applying=call('apply',{id:stage.id});
 await new Promise(resolve=>setTimeout(resolve,150));
 const statusDuringBuild=await fetch(base+'/api/deploy/status',{headers:{'X-Publisher-Token':token},signal:AbortSignal.timeout(3000)});assert.equal(statusDuringBuild.status,200);
 await applying;let output=await fs.readFile(path.join(site,'dist/index.html'),'utf8');assert.match(output,/Only selected material/);assert.doesNotMatch(output,/DO_NOT_EXPORT/);assert.ok(await fs.stat(path.join(site,'dist/pagefind/pagefind.js')));
 const originalPage=output,originalManifest=await fs.readFile(path.join(state,'current.json'),'utf8');
 await fs.writeFile(path.join(vault,'Public.md'),raw+'\n\nReviewed update.');
 plan=await call('analyze',{});stage=await call('prepare',{id:plan.id,approved:plan.assets.map(a=>a.key)});
 const pageSource=path.join(site,'src/pages/index.astro'),validPage=await fs.readFile(pageSource,'utf8');
 await fs.writeFile(pageSource,'---\nthrow Error("synthetic failed build");\n---\n<html></html>');
 const failed=await fetch(base+'/api/apply',{method:'POST',headers:{'X-Publisher-Token':token,Origin:base,'Content-Type':'application/json'},body:JSON.stringify({id:stage.id})});assert.equal(failed.status,400);
 assert.equal(await fs.readFile(path.join(site,'dist/index.html'),'utf8'),originalPage);assert.equal(await fs.readFile(path.join(state,'current.json'),'utf8'),originalManifest);
 await fs.writeFile(pageSource,validPage);await fs.writeFile(path.join(vault,'Public.md'),raw);
 await call('select',{selected:[]});plan=await call('analyze',{});assert.equal(plan.changes.removed.length,1);stage=await call('prepare',{id:plan.id,approved:[]});await call('apply',{id:stage.id});
 output=await fs.readFile(path.join(site,'dist/index.html'),'utf8');assert.doesNotMatch(output,/Only selected material/);assert.deepEqual(await fs.readdir(path.join(site,'public/published-assets')),[]);
 assert.equal(await fs.readFile(path.join(vault,'Public.md'),'utf8'),raw);
 await fs.writeFile(path.join(project,'docs/publisher-integration.json'),JSON.stringify({passed:true,scope:'synthetic isolated vault and site only',checks:['service identity','preview URL','default private','session and origin checks','explicit selection','thumbnail','attachment approval','markdown preview','Astro build','Pagefind index','failed build restores content and preview','withdrawal','original preserved']},null,2));
});
